from pathlib import Path

path = Path("src/App.jsx")
text = path.read_text(encoding="utf-8")

old = '''      <style>{`@media(max-width:860px){.dn{display:none!important}.mt{display:block!important}.mm{display:block!important}.nav-shell{padding:0 20px!important;height:72px!important}.nav-logo{height:38px!important;max-width:calc(100vw - 100px)!important}}@media(max-width:640px){h1{font-size:32px!important}h2{font-size:26px!important}section{padding-left:24px!important;padding-right:24px!important}button{width:100%!important;text-align:center}.home-hero{min-height:100svh!important;padding-top:80px!important}.home-hero-content{padding:0 0 56px!important}.home-hero-title{font-size:32px!important;line-height:1.08!important;margin-bottom:24px!important}.home-hero-copy{font-size:16px!important;line-height:1.65!important;max-width:360px!important}.contact-hero{padding-top:112px!important;padding-bottom:64px!important}}`}</style>'''

new = '''      <style>{`@media(max-width:860px){.dn{display:none!important}.nav-shell{position:relative!important;padding:0 20px!important;height:72px!important;width:100%!important;max-width:100vw!important;box-sizing:border-box!important;overflow:visible!important}.nav-logo{height:38px!important;max-width:calc(100vw - 96px)!important;width:auto!important}.mt{display:block!important;position:absolute!important;right:14px!important;top:12px!important;z-index:1003!important;box-sizing:border-box!important}.mm{display:block!important;position:fixed!important;top:72px!important;left:0!important;right:0!important;width:100vw!important;max-width:100vw!important;box-sizing:border-box!important;padding:20px 24px 28px!important;z-index:1001!important}}@media(max-width:640px){html,body,#root{max-width:100%!important;overflow-x:hidden!important}h1{font-size:32px!important}h2{font-size:26px!important}section{padding-left:24px!important;padding-right:24px!important;max-width:100vw!important;box-sizing:border-box!important}button{width:100%!important;max-width:100%!important;box-sizing:border-box!important;text-align:center}.home-hero{min-height:100svh!important;padding-top:80px!important}.home-hero-content{padding:0 0 56px!important}.home-hero-title{font-size:32px!important;line-height:1.08!important;margin-bottom:24px!important}.home-hero-copy{font-size:16px!important;line-height:1.65!important;max-width:360px!important}.contact-hero{padding-top:112px!important;padding-bottom:64px!important}}`}</style>'''

if text.count(old) != 1:
    raise SystemExit(f"Expected one mobile nav style block, found {text.count(old)}")

path.write_text(text.replace(old, new, 1), encoding="utf-8")
