import { useState, useEffect, useRef, useCallback } from "react";
/* ACCURATE DESIGNS V3.2 — Visual elevation. Strategy from V3.1 preserved. Warmer palette, editorial spacing, cinematic hero, Playfair Display serif. */
const fl=document.createElement("link");fl.href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,400;0,500;0,600;1,400;1,500&family=Outfit:wght@200;300;400;500;600&display=swap";fl.rel="stylesheet";document.head.appendChild(fl);
const C={black:"#080808",deep:"#1E1E1E",smoke:"#3A3632",cream:"#F5F1EB",warm:"#FAF8F4",orange:"#C96A2B",stone:"#CFC7BC",muted:"#908981",faint:"#E5DFD7",text:"#4A4540",tw:"#FFFFFF"};
const sf={fontFamily:"'Playfair Display','Georgia',serif"};const sn={fontFamily:"'Outfit',sans-serif"};
function useFI(){const r=useRef(null);const[v,sV]=useState(false);useEffect(()=>{const e=r.current;if(!e)return;const o=new IntersectionObserver(([x])=>{if(x.isIntersecting){sV(true);o.disconnect()}},{threshold:0.1});o.observe(e);return()=>o.disconnect()},[]);return{ref:r,style:{opacity:v?1:0,transform:v?"translateY(0)":"translateY(20px)",transition:"opacity 0.9s cubic-bezier(.25,.46,.45,.94),transform 0.9s cubic-bezier(.25,.46,.45,.94)"}};}
function F({children,delay=0}){const f=useFI();return <div ref={f.ref} style={{...f.style,transitionDelay:`${delay}s`}}>{children}</div>}

const PROJECTS=[
{id:"ashbury",name:"Ashbury Estate",location:"Oakville",sqft:"4,200",type:"Custom Home",lens:"Complex Site Resolution",img:"https://accuratedesigns.ca/wp-content/uploads/2023/09/DAV9668-768x511.jpg",challenge:"A steeply sloped lot with complex grading requirements had previously stalled with another designer after their plans were rejected at permit review.",solution:"We redesigned the foundation to work with the grade, resolved drainage and retaining wall conflicts in the drawings, and submitted a coordinated permit package.",result:"Approved on first submission. Construction proceeded without a single structural change order."},
{id:"country-heights",name:"Country Heights",location:"Milton",sqft:"3,800",type:"Custom Home",lens:"Structural Coordination",img:"https://accuratedesigns.ca/wp-content/uploads/2017/01/Brett-Custom-Homes-7-1.jpg",challenge:"The clients wanted a Georgian-inspired exterior with a fully modern open-concept interior — two design languages that typically conflict in structural layout and window placement.",solution:"A structural steel strategy allowed large interior spans while maintaining the symmetrical window pattern. Every beam location was coordinated with mechanical runs before permit submission.",result:"Zero RFIs on structural or mechanical coordination. The home maintains its period-appropriate facade while delivering the open living spaces the family needed."},
{id:"stephens",name:"Stephens Crescent",location:"Oakville",sqft:"3,500",type:"Custom Home",lens:"Zoning Optimization",img:"https://accuratedesigns.ca/wp-content/uploads/2017/01/DAV9625-768x648.jpg",challenge:"A corner lot with overlapping setback requirements from two frontages. The previous designer\u2019s plans left significant buildable area unused.",solution:"Our zoning analysis identified allowable projections and setback exceptions that the previous plans had missed, unlocking an additional 400 square feet within the same envelope.",result:"A full additional bedroom and ensuite — no variance required. Permit approval with three minor comments, all resolved in one resubmission."},
{id:"rebecca",name:"Rebecca Street",location:"Oakville",sqft:"4,100",type:"Custom Home",lens:"Budget-Conscious Planning",img:"https://accuratedesigns.ca/wp-content/uploads/2023/02/Brett-Custom-Homes-10-768x420.jpg",challenge:"A growing family needed to balance formal entertaining spaces with practical everyday living — without exceeding what the neighbourhood would support at resale.",solution:"A central gallery separates public and private zones, allowing family areas to be finished to a different specification than formal spaces — reducing costs where they wouldn\u2019t affect lifestyle or value.",result:"Project came in under the original budget estimate. Every room is used daily — nothing was built that the family doesn\u2019t need."},
{id:"spring-garden",name:"Spring Garden",location:"GTA",sqft:"5,200",type:"Custom Home",lens:"Heritage + Site Sensitivity",img:"https://accuratedesigns.ca/wp-content/uploads/2017/01/Spring_Garden_2.jpg",challenge:"Villa-scale home requiring distinct living zones on a lot with significant grade changes and three heritage trees under preservation requirements.",solution:"The plan organized around a central courtyard providing natural zone separation. Foundation design was coordinated around root protection zones for all three heritage trees.",result:"All heritage trees preserved. The courtyard eliminated the need for a formal hallway, converting ~280 sq ft of circulation into usable living area."},
{id:"taplow",name:"Taplow",location:"GTA",sqft:"3,600",type:"Addition + Renovation",lens:"Addition Without Underpinning",img:"https://accuratedesigns.ca/wp-content/uploads/2023/09/Taplow-2-768x511.jpg",challenge:"A second-storey addition needed to double living space while working within the existing foundation\u2019s load capacity.",solution:"Structural analysis identified which walls could carry additional load. The second storey was designed to concentrate loads on existing bearing points, avoiding foundation underpinning entirely.",result:"Completed without foundation modifications — saving an estimated $45,000\u2013$60,000 in underpinning costs that two other firms had quoted as unavoidable."},
];
const TEST=[
{text:"Accurate Designs was the best choice we made for our custom home build. Brett walked us through the entire process and designed exactly what we envisioned. The permit process was a breeze.",author:"Custom Home Client",location:"Oakville, ON",label:"Smooth Permit Experience"},
{text:"Honesty, transparency, commitment and professionalism. Brett took full responsibility and delivered on time, on budget.",author:"Majdi T.",location:"Mississauga, ON",label:"On Time, On Budget"},
{text:"Brett helped us design a phenomenal layout addressing all of our needs. The end result was beautiful.",author:"Residential Client",location:"Oakville, ON",label:"Design That Delivered"},
{text:"I worked with Brett over ten years ago — he designed my home. Very informative, took charge through the permit process. Highly recommend.",author:"Attard Plumbing Ltd.",location:"Toronto, ON",label:"Builder Perspective"},
];

function Nav({page,go}){const[sc,setSc]=useState(false);const[op,setOp]=useState(false);useEffect(()=>{const h=()=>setSc(window.scrollY>50);window.addEventListener("scroll",h);return()=>window.removeEventListener("scroll",h)},[]);const nv=p=>{go(p);setOp(false)};const its=[{id:"services",l:"Services"},{id:"portfolio",l:"Portfolio"},{id:"process",l:"Process"},{id:"owner-rep",l:"Owner Rep"},{id:"about",l:"About"},{id:"contact",l:"Contact"}];
return(<nav style={{position:"fixed",top:0,left:0,right:0,zIndex:1000,background:sc?"rgba(8,8,8,0.97)":"transparent",backdropFilter:sc?"blur(20px)":"none",transition:"all 0.6s",borderBottom:sc?"1px solid rgba(201,106,43,0.08)":"none"}}><div style={{maxWidth:1240,margin:"0 auto",padding:"0 40px",display:"flex",alignItems:"center",justifyContent:"space-between",height:sc?64:84,transition:"height 0.6s"}}><div style={{cursor:"pointer",display:"flex",alignItems:"center",gap:16}} onClick={()=>nv("home")}><div style={{width:34,height:34,border:"1px solid rgba(255,255,255,0.2)",display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{...sf,fontSize:15,fontWeight:500,color:C.tw,letterSpacing:1.5}}>AD</span></div><span style={{...sn,fontSize:10,fontWeight:300,letterSpacing:5,color:"rgba(255,255,255,0.35)",textTransform:"uppercase"}}>Accurate Designs</span></div>
<div style={{display:"flex",gap:36,alignItems:"center"}} className="dn">{its.map(i=><span key={i.id} onClick={()=>nv(i.id)} style={{...sn,fontSize:10.5,fontWeight:400,letterSpacing:2.5,textTransform:"uppercase",color:page===i.id?C.orange:"rgba(255,255,255,0.45)",cursor:"pointer",transition:"color 0.4s",paddingBottom:2,borderBottom:page===i.id?`1px solid ${C.orange}`:"1px solid transparent"}} onMouseEnter={e=>{if(page!==i.id)e.target.style.color="rgba(255,255,255,0.8)"}} onMouseLeave={e=>{if(page!==i.id)e.target.style.color="rgba(255,255,255,0.45)"}}>{i.l}</span>)}</div>
<div className="mt" style={{display:"none",cursor:"pointer",padding:10}} onClick={()=>setOp(!op)}>{[0,1,2].map(i=><div key={i} style={{width:22,height:1.5,background:"rgba(255,255,255,0.5)",marginBottom:i<2?6:0,transition:"all 0.3s",...(op&&i===0?{transform:"rotate(45deg) translate(5px,5px)"}:{}),...(op&&i===1?{opacity:0}:{}),...(op&&i===2?{transform:"rotate(-45deg) translate(5px,-5px)"}:{})}}/>)}</div></div>
{op&&<div className="mm" style={{display:"none",background:"rgba(8,8,8,0.98)",padding:"20px 40px 28px",borderTop:"1px solid rgba(255,255,255,0.04)"}}>{its.map(i=><div key={i.id} onClick={()=>nv(i.id)} style={{...sn,padding:"16px 0",fontSize:12,letterSpacing:2.5,textTransform:"uppercase",color:page===i.id?C.orange:"rgba(255,255,255,0.4)",cursor:"pointer",borderBottom:"1px solid rgba(255,255,255,0.03)"}}>{i.l}</div>)}</div>}
<style>{`@media(max-width:860px){.dn{display:none!important}.mt{display:block!important}.mm{display:block!important}}@media(max-width:640px){h1{font-size:32px!important}h2{font-size:26px!important}section{padding-left:24px!important;padding-right:24px!important}button{width:100%!important;text-align:center}}`}</style></nav>)}

function Sec({children,bg,py=140,wide}){return <section style={{background:bg||C.cream,padding:`${py}px 40px`}}><div style={{maxWidth:wide?1100:940,margin:"0 auto"}}>{children}</div></section>}
function Lbl({children,light}){return <div style={{...sn,fontSize:10,fontWeight:500,letterSpacing:4,textTransform:"uppercase",color:light?"rgba(201,106,43,0.7)":C.orange,marginBottom:24}}>{children}</div>}
function Ttl({children,light,size}){return <h2 style={{...sf,fontSize:size||"clamp(32px,4.5vw,52px)",fontWeight:400,color:light?C.cream:C.black,lineHeight:1.12,marginBottom:24,letterSpacing:-0.3}}>{children}</h2>}
function Bd({children,light,max}){return <p style={{...sn,fontSize:15,fontWeight:300,lineHeight:1.9,color:light?"rgba(245,241,235,0.5)":C.muted,maxWidth:max||600,letterSpacing:0.15}}>{children}</p>}
function Bt({children,onClick,outline,light,style:s}){const dk=light&&outline;const b={...sn,padding:"16px 44px",fontSize:10,fontWeight:500,letterSpacing:3,textTransform:"uppercase",cursor:"pointer",transition:"all 0.4s",border:`1px solid ${dk?"rgba(255,255,255,0.15)":outline?"rgba(201,106,43,0.35)":C.orange}`,background:outline?"transparent":C.orange,color:dk?"rgba(255,255,255,0.45)":outline?C.orange:C.cream,...s};return <button style={b} onClick={onClick} onMouseEnter={e=>{e.target.style.background=C.orange;e.target.style.color=C.cream;e.target.style.borderColor=C.orange}} onMouseLeave={e=>{e.target.style.background=outline?"transparent":C.orange;e.target.style.color=dk?"rgba(255,255,255,0.45)":outline?C.orange:C.cream;e.target.style.borderColor=dk?"rgba(255,255,255,0.15)":outline?"rgba(201,106,43,0.35)":C.orange}}>{children}</button>}
function Inp({label,type="text",textarea}){const b={...sn,width:"100%",padding:"16px 0 14px",fontSize:14,fontWeight:300,color:C.black,background:"transparent",border:"none",borderBottom:`1px solid ${C.stone}`,outline:"none",letterSpacing:0.3,boxSizing:"border-box",transition:"border-color 0.4s"};return <div style={{marginBottom:30}}><label style={{...sn,fontSize:9.5,fontWeight:500,letterSpacing:2.5,textTransform:"uppercase",color:C.muted,display:"block",marginBottom:10}}>{label}</label>{textarea?<textarea rows={3} style={{...b,resize:"none",fontFamily:"'Outfit',sans-serif"}} onFocus={e=>e.target.style.borderBottomColor=C.orange} onBlur={e=>e.target.style.borderBottomColor=C.stone}/>:<input type={type} style={b} onFocus={e=>e.target.style.borderBottomColor=C.orange} onBlur={e=>e.target.style.borderBottomColor=C.stone}/>}</div>}
function Sel({label,options}){return <div style={{marginBottom:30}}><label style={{...sn,fontSize:9.5,fontWeight:500,letterSpacing:2.5,textTransform:"uppercase",color:C.muted,display:"block",marginBottom:10}}>{label}</label><select style={{...sn,width:"100%",padding:"16px 0 14px",fontSize:14,fontWeight:300,color:C.black,background:"transparent",border:"none",borderBottom:`1px solid ${C.stone}`,outline:"none",boxSizing:"border-box",cursor:"pointer"}}>{options.map(o=><option key={o}>{o}</option>)}</select></div>}
function Stats({light}){const s=[{n:"25+",l:"Years in Practice"},{n:"300+",l:"Residential Projects"},{n:"2\u20133",l:"Typical Review Comments"},{n:"$500K\u2013$20M+",l:"Project Range"}];return <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(170px,1fr))",gap:40,padding:"56px 0",borderTop:`1px solid ${light?"rgba(245,241,235,0.06)":C.faint}`,borderBottom:`1px solid ${light?"rgba(245,241,235,0.06)":C.faint}`}}>{s.map((x,i)=><div key={i} style={{textAlign:"center"}}><div style={{...sf,fontSize:"clamp(26px,3.2vw,38px)",fontWeight:400,color:light?C.cream:C.black,marginBottom:6}}>{x.n}</div><div style={{...sn,fontSize:9.5,fontWeight:400,letterSpacing:2.5,textTransform:"uppercase",color:light?"rgba(245,241,235,0.3)":C.muted}}>{x.l}</div></div>)}</div>}
function PInfo({p}){return <div style={{paddingTop:8}}><div style={{...sn,fontSize:9,fontWeight:500,letterSpacing:3,color:C.orange,marginBottom:12,textTransform:"uppercase"}}>{p.lens}</div><h3 style={{...sf,fontSize:"clamp(24px,2.8vw,32px)",color:C.black,marginBottom:6,lineHeight:1.15}}>{p.name}</h3><div style={{...sn,fontSize:11,fontWeight:300,color:C.muted,marginBottom:24,display:"flex",gap:12,flexWrap:"wrap"}}><span>{p.type}</span><span style={{color:C.stone}}>·</span><span>{p.location}</span><span style={{color:C.stone}}>·</span><span>{p.sqft} sf</span></div>{[{l:"Challenge",v:p.challenge},{l:"Approach",v:p.solution},{l:"Result",v:p.result}].map((r,j)=><div key={j} style={{marginBottom:16}}><div style={{...sn,fontSize:9.5,fontWeight:600,letterSpacing:2,color:C.smoke,marginBottom:5,textTransform:"uppercase"}}>{r.l}</div><p style={{...sn,fontSize:13,fontWeight:300,lineHeight:1.7,color:C.muted}}>{r.v}</p></div>)}</div>}

function HomePage({go}){return <>
{/* HERO */}
<section style={{position:"relative",minHeight:"100vh",display:"flex",alignItems:"flex-end",background:C.black,overflow:"hidden"}}><div style={{position:"absolute",inset:0}}><img src="https://accuratedesigns.ca/wp-content/uploads/2023/09/DAV9668-768x511.jpg" alt="" style={{width:"100%",height:"100%",objectFit:"cover",filter:"grayscale(12%) brightness(0.62) saturate(1.1)"}}/></div><div style={{position:"absolute",inset:0,background:"linear-gradient(to top,rgba(8,8,8,0.93) 0%,rgba(30,28,24,0.45) 45%,rgba(8,8,8,0.15) 100%)"}}/>
<div style={{position:"relative",zIndex:2,maxWidth:1100,width:"100%",margin:"0 auto",padding:"0 40px 100px"}}><F><Lbl light>Custom Homes · Additions · Major Renovations</Lbl></F><F delay={0.12}><h1 style={{...sf,fontSize:"clamp(32px,5.5vw,64px)",fontWeight:400,color:C.cream,lineHeight:1.1,marginBottom:32,maxWidth:740}}>We design homes that are resolved on paper before they cost you on site.</h1></F><F delay={0.24}><p style={{...sn,fontSize:15,fontWeight:300,lineHeight:1.85,color:"rgba(245,241,235,0.45)",maxWidth:460}}>Construction-aware residential design across the Greater Toronto Area. Building knowledge in the design process from day one — so fewer decisions are left to the job site.</p></F><F delay={0.36}><div style={{display:"flex",gap:16,marginTop:48,flexWrap:"wrap"}}><Bt onClick={()=>go("contact")}>Book a Project Consultation</Bt><Bt outline light onClick={()=>go("portfolio")}>View Our Work</Bt></div></F></div></section>

<Sec py={64} bg={C.warm}><Stats/></Sec>

{/* WHY IT MATTERS */}
<Sec py={140}><F><Lbl>Why It Matters</Lbl><Ttl>The most expensive decisions are the ones made too late.</Ttl></F><F delay={0.08}><Bd>When zoning, structure, mechanical systems, and budget are coordinated during design — not after — projects cost less to build, permit faster, and produce better outcomes. That coordination is the foundation of everything we do.</Bd></F>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(270px,1fr))",gap:56,marginTop:72}}>{[{t:"Construction-Aware Design",b:"Every drawing is developed with buildability in mind. We coordinate structure, mechanical, and architectural systems during design — so the builder receives instructions, not questions."},{t:"Fewer Surprises Later",b:"When decisions are resolved on paper, change orders drop, timelines hold, and the gap between design intent and construction reality closes."},{t:"Clarity Before You Commit",b:"Before you invest in design or sign a contract, we help you understand what your lot allows, what the code requires, and what the project will realistically cost."}].map((x,i)=><F key={i} delay={i*0.08}><div style={{borderTop:`1px solid ${C.faint}`,paddingTop:32}}><h3 style={{...sn,fontSize:15,fontWeight:500,color:C.black,marginBottom:14,letterSpacing:0.2}}>{x.t}</h3><p style={{...sn,fontSize:13.5,fontWeight:300,lineHeight:1.8,color:C.muted}}>{x.b}</p></div></F>)}</div></Sec>

{/* WHAT WE DO */}
<Sec py={120} bg={C.warm}><F><Lbl>What We Do</Lbl><Ttl size="clamp(28px,3.5vw,40px)">Design and build services for custom residential projects.</Ttl></F>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:40,marginTop:56}}>{[{t:"Custom Homes",d:"Full architectural design, permit documentation, and construction for new builds across the GTA."},{t:"Additions + Renovations",d:"Second-storey additions, gut renovations, and structural reconfigurations — with the same documentation precision as a new build."},{t:"Permit-Ready Documentation",d:"OBC-compliant architectural, structural, and mechanical drawings coordinated as a single package."},{t:"Owner Representation",d:"Independent project oversight for homeowners who want an experienced technical advocate in their corner."}].map((x,i)=><F key={i} delay={i*0.06}><div style={{borderTop:`1px solid ${C.faint}`,paddingTop:28}}><h4 style={{...sn,fontSize:14,fontWeight:500,color:C.black,marginBottom:10}}>{x.t}</h4><p style={{...sn,fontSize:13,fontWeight:300,lineHeight:1.75,color:C.muted}}>{x.d}</p></div></F>)}</div>
<div style={{marginTop:52}}><Bt outline onClick={()=>go("services")}>View All Services</Bt></div></Sec>

{/* WHO WE WORK WITH */}
<Sec py={100}><F><Lbl>Who We Work With</Lbl><Ttl size="clamp(26px,3.2vw,36px)">We're the right fit when the details matter.</Ttl>
<div style={{display:"grid",gridTemplateColumns:"1.2fr 1fr",gap:48,marginTop:40}} className="wg"><div>{["Homeowners planning a custom home or estate-scale build","Major additions and structural renovations where coordination is critical","Projects where zoning, conservation authority, or site complexity requires careful analysis","Clients who value thorough planning over fast sketches"].map((x,i)=><div key={i} style={{display:"flex",gap:14,marginBottom:18}}><span style={{...sn,fontSize:12,color:C.orange,fontWeight:500,minWidth:14,paddingTop:2}}>—</span><span style={{...sn,fontSize:14,fontWeight:300,color:C.text,lineHeight:1.7}}>{x}</span></div>)}</div>
<div style={{borderLeft:`1px solid ${C.faint}`,paddingLeft:32,display:"flex",alignItems:"center"}}><p style={{...sf,fontSize:16,fontStyle:"italic",color:C.stone,lineHeight:1.7}}>We are not the right choice for permit-only drafting with minimal design coordination. Our value is in the thinking behind the drawings.</p></div></div></F></Sec>

{/* SELECTED WORK */}
<section style={{background:C.black,padding:"140px 40px"}}><div style={{maxWidth:1240,margin:"0 auto"}}><F><Lbl light>Selected Work</Lbl></F><F delay={0.08}><Ttl light>Featured Projects</Ttl></F>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(320px,1fr))",gap:24,marginTop:64}}>{PROJECTS.slice(0,3).map((p,i)=><F key={p.id} delay={i*0.1}><div style={{cursor:"pointer"}} onClick={()=>go("portfolio")}><div style={{position:"relative",paddingBottom:"75%",overflow:"hidden"}}><img src={p.img} alt={p.name} style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"cover",transition:"transform 0.8s,filter 0.8s",filter:"grayscale(15%) brightness(0.85)"}} onMouseEnter={e=>{e.target.style.transform="scale(1.04)";e.target.style.filter="grayscale(0) brightness(1)"}} onMouseLeave={e=>{e.target.style.transform="scale(1)";e.target.style.filter="grayscale(15%) brightness(0.85)"}}/></div>
<div style={{padding:"22px 0 0"}}><div style={{...sn,fontSize:9,fontWeight:500,letterSpacing:3,color:C.orange,marginBottom:10,textTransform:"uppercase",opacity:0.8}}>{p.lens}</div><div style={{display:"flex",justifyContent:"space-between",alignItems:"baseline",marginBottom:6}}><span style={{...sf,fontSize:18,fontWeight:400,color:C.cream}}>{p.name}</span><span style={{...sn,fontSize:11,fontWeight:300,color:"rgba(245,241,235,0.25)"}}>{p.sqft} sf</span></div><p style={{...sn,fontSize:12,fontWeight:300,lineHeight:1.6,color:"rgba(245,241,235,0.3)"}}>{p.challenge.substring(0,100)}...</p></div></div></F>)}</div>
<div style={{marginTop:52}}><Bt outline light onClick={()=>go("portfolio")}>View All Projects</Bt></div></div></section>

{/* TESTIMONIAL */}
<Sec py={120}><F><div style={{maxWidth:580}}><div style={{...sn,fontSize:9,fontWeight:500,letterSpacing:3,color:C.orange,marginBottom:20,textTransform:"uppercase"}}>Smooth Permit Experience</div><p style={{...sf,fontSize:"clamp(19px,2.5vw,26px)",fontStyle:"italic",fontWeight:400,color:C.smoke,lineHeight:1.55,marginBottom:28}}>"Brett walked us through the entire process and designed exactly what we envisioned. The permit process was a breeze."</p><div style={{...sn,fontSize:12,fontWeight:500,color:C.black,letterSpacing:0.5}}>Custom Home Client</div><div style={{...sn,fontSize:11,fontWeight:300,color:C.muted}}>Oakville, ON</div></div></F></Sec>

{/* PROCESS PREVIEW */}
<Sec py={120} bg={C.warm}><F><Lbl>How We Work</Lbl><Ttl size="clamp(28px,3.5vw,40px)">A structured process that resolves complexity early.</Ttl></F>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:48,marginTop:56}}>{[{n:"01",t:"Discovery + Feasibility",d:"We assess your lot, zoning, budget range, and goals before any design work begins."},{n:"02",t:"Design Resolution",d:"We iterate until every decision is resolved — structure, systems, materials, cost."},{n:"03",t:"Permit + Approvals",d:"Complete, coordinated documentation submitted for efficient review."},{n:"04",t:"Build Readiness",d:"Drawings detailed enough for accurate pricing and confident construction — or our team builds it directly."}].map((x,i)=><F key={i} delay={i*0.06}><div><div style={{...sf,fontSize:28,fontWeight:400,color:C.orange,opacity:0.35,marginBottom:14}}>{x.n}</div><h4 style={{...sn,fontSize:15,fontWeight:500,color:C.black,marginBottom:10}}>{x.t}</h4><p style={{...sn,fontSize:13,fontWeight:300,lineHeight:1.75,color:C.muted}}>{x.d}</p></div></F>)}</div>
<div style={{marginTop:48}}><Bt outline onClick={()=>go("process")}>See Full Process</Bt></div></Sec>

{/* LEARN WITH BRETT */}
<Sec py={120}><F><Lbl>Learn with Brett</Lbl><Ttl size="clamp(26px,3.2vw,38px)">Planning insights for homeowners who want to get it right the first time.</Ttl><Bd max={520}>Before you hire anyone, there are decisions that quietly shape the cost, timeline, and outcome of your entire project.</Bd></F>
<div style={{marginTop:56}}>
<F><div style={{background:C.warm,padding:"48px 44px",borderLeft:`3px solid ${C.orange}`,marginBottom:40}}><div style={{...sn,fontSize:9,fontWeight:500,letterSpacing:3,color:C.orange,marginBottom:14,textTransform:"uppercase"}}>Featured Resource</div><h3 style={{...sf,fontSize:"clamp(22px,2.5vw,28px)",fontWeight:400,color:C.black,lineHeight:1.25,marginBottom:14}}>The Decisions That Lock In Cost</h3><p style={{...sn,fontSize:14,fontWeight:300,lineHeight:1.8,color:C.muted,maxWidth:480,marginBottom:24}}>Which early-stage choices quietly determine 80% of your construction budget — and how to make them with full context before committing to design or construction.</p><Bt outline onClick={()=>go("contact")}>Request the Planning Guide</Bt></div></F>
<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:36}}>
{[{t:"Before You Sign Anything",d:"What to clarify about scope, budget, and expectations before committing to a design contract or builder agreement."},{t:"What Your Lot Actually Allows",d:"How zoning bylaws, setbacks, easements, and conservation overlays determine what can be built."}].map((x,i)=>
<F key={i} delay={i*0.06}><div style={{borderTop:`1px solid ${C.faint}`,paddingTop:28}}><h4 style={{...sf,fontSize:16,fontWeight:400,fontStyle:"italic",color:C.smoke,marginBottom:10}}>{x.t}</h4><p style={{...sn,fontSize:13,fontWeight:300,lineHeight:1.75,color:C.muted}}>{x.d}</p></div></F>)}</div></div>
<div style={{marginTop:36}}><Bt outline onClick={()=>go("contact")}>Explore All Planning Resources</Bt></div></Sec>

{/* OWNER REP TEASER */}
<section style={{background:C.deep,padding:"120px 40px"}}><div style={{maxWidth:1100,margin:"0 auto",display:"grid",gridTemplateColumns:"1.1fr 0.9fr",gap:80,alignItems:"center"}} className="og"><F><div><Lbl light>Independent Advisory</Lbl><Ttl light size="clamp(28px,3.5vw,42px)">Owner Representation</Ttl><p style={{...sn,fontSize:14,fontWeight:300,lineHeight:1.9,color:"rgba(245,241,235,0.45)",marginBottom:40}}>An experienced technical advocate who reads drawings, understands construction, and works exclusively in your interest. Available for projects at any stage.</p><Bt outline light onClick={()=>go("owner-rep")}>Learn More</Bt></div></F>
<F delay={0.12}><div style={{borderLeft:"1px solid rgba(201,106,43,0.15)",paddingLeft:40}}><div style={{...sf,fontSize:"clamp(20px,2.8vw,28px)",fontStyle:"italic",fontWeight:400,color:"rgba(245,241,235,0.18)",lineHeight:1.55}}>"If a decision is not made on paper, it will be made on site."</div></div></F></div></section>

{/* CTA */}
<Sec py={120} bg={C.cream}><F><div style={{textAlign:"center",maxWidth:560,margin:"0 auto"}}><Lbl>Next Step</Lbl><Ttl size="clamp(26px,3.5vw,40px)">Planning a custom home, addition, or renovation?</Ttl><p style={{...sn,fontSize:15,fontWeight:300,color:C.muted,lineHeight:1.85,marginBottom:44}}>A project consultation helps clarify goals, assess feasibility, and outline next steps. No cost, no obligation.</p><div style={{display:"flex",gap:16,justifyContent:"center",flexWrap:"wrap"}}><Bt onClick={()=>go("contact")}>Book a Project Consultation</Bt><Bt outline onClick={()=>go("contact")}>Request a Feasibility Review</Bt></div></div></F></Sec>

<style>{`@media(max-width:860px){.wg{grid-template-columns:1fr!important}.og{grid-template-columns:1fr!important}}`}</style>
</>}

function ServicesPage({go}){const sv=[{label:"Design-Build",title:"Custom Home Design + Build",body:"We design and build custom homes under one roof. Because the same team that creates the drawings oversees the build, decisions carry through to the site without the gaps and reinterpretations that occur when design and construction are handled separately.",outcome:"The result is a home that matches the original intent, built on a validated budget, with significantly fewer change orders.",cta:"Book a Project Consultation"},{label:"Additions + Renovations",title:"Major Additions + Renovations",body:"Second-storey additions, gut renovations, and structural reconfigurations present challenges new builds don\u2019t — existing foundation capacity, load paths through older framing, integrating new systems with existing infrastructure. We bring the same coordination to renovation work that most firms reserve for new construction.",outcome:"Every existing condition is assessed in the drawings, so the builder encounters fewer surprises when the walls come down.",cta:"Book a Project Consultation"},{label:"Permit Documentation",title:"Permit-Ready Documentation",body:"We prepare complete permit packages — architectural, structural, and mechanical drawings coordinated as a single submission. Our familiarity with OBC requirements and municipal review processes means submissions are thorough, correctly formatted, and address what reviewers look for.",outcome:"Our submissions typically receive 2\u20133 review comments — reducing approval timelines and eliminating the costly resubmission cycles that delay many projects.",cta:"Request a Quote"},{label:"Feasibility + Planning",title:"Pre-Design Feasibility",body:"Before committing to design, understand what your lot allows, what the zoning requires, and what the realistic budget range is. This is especially important for properties with complex zoning overlays, conservation authority involvement, or site conditions that affect buildable area.",outcome:"A feasibility review typically takes 1\u20132 weeks and prevents the most expensive category of mistake: designing something that can\u2019t be built, permitted, or afforded.",cta:"Request a Feasibility Review"}];
return <><section style={{background:C.black,padding:"180px 40px 120px"}}><div style={{maxWidth:940,margin:"0 auto"}}><F><Lbl light>What We Do</Lbl><Ttl light>Services</Ttl></F><F delay={0.1}><Bd light max={520}>Every service is built on the same principle: resolve decisions on paper, before they become expensive on site.</Bd></F></div></section>
<Sec py={80} bg={C.warm}><F><Lbl>Where to Start</Lbl><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(250px,1fr))",gap:36}}>{[{s:"You\u2019re ready to design and build a custom home",a:"Project Consultation",p:"contact"},{s:"You\u2019re early-stage and unsure about feasibility",a:"Feasibility Review",p:"contact"},{s:"You\u2019re mid-project and need oversight",a:"Representation Consultation",p:"owner-rep"}].map((r,i)=><div key={i} style={{borderTop:`1px solid ${C.faint}`,paddingTop:24,cursor:"pointer"}} onClick={()=>go(r.p)}><p style={{...sn,fontSize:13,fontWeight:300,color:C.muted,lineHeight:1.65,marginBottom:14}}>{r.s}</p><span style={{...sn,fontSize:10,fontWeight:500,color:C.orange,letterSpacing:2,textTransform:"uppercase"}}>{r.a} \u2192</span></div>)}</div></F></Sec>
{sv.map((s,i)=><Sec key={i} py={120} bg={i%2===0?C.cream:C.warm}><F><div style={{display:"grid",gridTemplateColumns:"180px 1fr",gap:56,alignItems:"start"}} className="sg"><div style={{...sn,fontSize:10,fontWeight:500,letterSpacing:3.5,textTransform:"uppercase",color:C.orange,paddingTop:8}}>{s.label}</div><div><h3 style={{...sf,fontSize:"clamp(26px,3vw,36px)",color:C.black,marginBottom:24,lineHeight:1.15}}>{s.title}</h3><p style={{...sn,fontSize:14,fontWeight:300,lineHeight:1.9,color:C.muted,maxWidth:520,marginBottom:16}}>{s.body}</p><p style={{...sn,fontSize:14,fontWeight:400,lineHeight:1.9,color:C.text,maxWidth:520,marginBottom:36}}>{s.outcome}</p><Bt outline onClick={()=>go("contact")}>{s.cta}</Bt></div></div></F></Sec>)}
<section style={{background:C.deep,padding:"100px 40px",textAlign:"center"}}><Ttl light size="clamp(26px,3vw,36px)">Not sure where to start?</Ttl><p style={{...sn,fontSize:14,fontWeight:300,color:"rgba(245,241,235,0.35)",maxWidth:400,margin:"0 auto 40px"}}>A short conversation will help clarify the right path forward.</p><Bt onClick={()=>go("contact")}>Book a Project Consultation</Bt></section>
<style>{`@media(max-width:860px){.sg{grid-template-columns:1fr!important}}`}</style></>}

function PortfolioPage({go}){return <><section style={{background:C.black,padding:"180px 40px 120px"}}><div style={{maxWidth:940,margin:"0 auto"}}><F><Lbl light>Our Work</Lbl><Ttl light>Portfolio</Ttl></F><F delay={0.1}><Bd light max={500}>Each project illustrates a specific challenge, the design thinking applied, and the outcome.</Bd></F></div></section>
<section style={{background:C.warm,padding:"80px 40px 40px"}}><div style={{maxWidth:1100,margin:"0 auto"}}>{PROJECTS.map((p,i)=><F key={p.id} delay={i*0.04}><div style={{marginBottom:80,paddingBottom:i<PROJECTS.length-1?80:0,borderBottom:i<PROJECTS.length-1?`1px solid ${C.faint}`:"none"}}><div style={{display:"grid",gridTemplateColumns:i%2===0?"1.2fr 1fr":"1fr 1.2fr",gap:56,alignItems:"start"}} className="pg">{i%2===0?<><div style={{position:"relative",paddingBottom:"72%",overflow:"hidden"}}><img src={p.img} alt={p.name} style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"cover",transition:"transform 0.8s,filter 0.6s",filter:"grayscale(6%) brightness(0.92)"}} onMouseEnter={e=>{e.target.style.transform="scale(1.03)";e.target.style.filter="grayscale(0) brightness(1)"}} onMouseLeave={e=>{e.target.style.transform="scale(1)";e.target.style.filter="grayscale(6%) brightness(0.92)"}}/></div><PInfo p={p}/></>:<><PInfo p={p}/><div style={{position:"relative",paddingBottom:"72%",overflow:"hidden"}}><img src={p.img} alt={p.name} style={{position:"absolute",inset:0,width:"100%",height:"100%",objectFit:"cover",transition:"transform 0.8s,filter 0.6s",filter:"grayscale(6%) brightness(0.92)"}} onMouseEnter={e=>{e.target.style.transform="scale(1.03)";e.target.style.filter="grayscale(0) brightness(1)"}} onMouseLeave={e=>{e.target.style.transform="scale(1)";e.target.style.filter="grayscale(6%) brightness(0.92)"}}/></div></>}</div></div></F>)}</div></section>
<section style={{background:C.deep,padding:"100px 40px",textAlign:"center"}}><Ttl light size="clamp(26px,3vw,36px)">Have a project in mind?</Ttl><p style={{...sn,fontSize:14,fontWeight:300,color:"rgba(245,241,235,0.35)",marginBottom:36}}>We'll assess feasibility and outline a clear path forward.</p><Bt onClick={()=>go("contact")}>Book a Project Consultation</Bt></section>
<style>{`@media(max-width:860px){.pg{grid-template-columns:1fr!important}}`}</style></>}

function ProcessPage({go}){const st=[{n:"01",t:"Discovery + Feasibility",d:"We assess your project — goals, lot, budget range, timeline, and existing decisions. We review zoning, identify constraints, and confirm feasibility before design begins. This phase regularly surfaces opportunities or risks that affect scope, cost, or timeline — far less expensive to address here than after drawings are underway."},{n:"02",t:"Design Development",d:"We resolve layout, structure, code compliance, mechanical coordination, and cost alignment through concept, schematic, and detailed design phases. Beam locations coordinate with duct runs, window headers with structural loads, plumbing stacks with usable floor area. The goal: a fully resolved document set with no decisions deferred to the builder."},{n:"03",t:"Permit + Approvals",d:"We submit complete, coordinated permit packages — architectural, structural, and mechanical. Our familiarity with OBC requirements and municipal processes means thorough documentation that addresses what reviewers look for. Our submissions typically receive 2\u20133 review comments, where many projects receive 10\u201315 or more."},{n:"04",t:"Build Readiness",d:"We ensure the builder has everything needed to price accurately and build confidently. Drawings answer most questions before they\u2019re asked. Budget is validated against real trade pricing. If we\u2019re providing design-build, our team carries this precision directly through construction."}];
return <><section style={{background:C.black,padding:"180px 40px 120px"}}><div style={{maxWidth:940,margin:"0 auto"}}><F><Lbl light>How We Work</Lbl><Ttl light>Process</Ttl></F><F delay={0.1}><Bd light max={480}>Each phase resolves complexity before it reaches the next — so decisions are deliberate, documentation is thorough, and the project stays on track.</Bd></F></div></section>
<Sec py={64} bg={C.warm}><F><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(200px,1fr))",gap:36}}>{["Fewer late-stage decisions","More accurate pricing","Smoother permit approvals","Cleaner builder handoff"].map((b,i)=><div key={i} style={{display:"flex",gap:12,alignItems:"center"}}><span style={{...sn,fontSize:12,color:C.orange,fontWeight:500}}>—</span><span style={{...sn,fontSize:13,fontWeight:400,color:C.text}}>{b}</span></div>)}</div></F></Sec>
<Sec py={120} bg={C.warm}>{st.map((s,i)=><F key={i} delay={i*0.06}><div style={{display:"grid",gridTemplateColumns:"90px 1fr",gap:40,marginBottom:i<st.length-1?80:0,paddingBottom:i<st.length-1?80:0,borderBottom:i<st.length-1?`1px solid ${C.faint}`:"none"}} className="prg"><div style={{...sf,fontSize:36,fontWeight:400,color:C.orange,opacity:0.3}}>{s.n}</div><div><h3 style={{...sn,fontSize:18,fontWeight:500,color:C.black,marginBottom:14}}>{s.t}</h3><p style={{...sn,fontSize:14,fontWeight:300,lineHeight:1.9,color:C.muted,maxWidth:560}}>{s.d}</p></div></div></F>)}</Sec>
<section style={{background:C.deep,padding:"100px 40px",textAlign:"center"}}><div style={{...sf,fontSize:"clamp(18px,2.5vw,24px)",fontStyle:"italic",fontWeight:400,color:"rgba(245,241,235,0.2)",maxWidth:480,margin:"0 auto 40px",lineHeight:1.55}}>"If a decision is not made on paper, it will be made on site."</div><Bt onClick={()=>go("contact")}>Request a Feasibility Review</Bt></section>
<style>{`@media(max-width:860px){.prg{grid-template-columns:1fr!important}}`}</style></>}

function OwnerRepPage({go}){return <><section style={{background:C.black,padding:"180px 40px 120px"}}><div style={{maxWidth:940,margin:"0 auto"}}><F><Lbl light>Independent Advisory</Lbl><Ttl light>Owner Representation</Ttl></F><F delay={0.1}><div style={{...sf,fontSize:"clamp(18px,2.2vw,23px)",fontStyle:"italic",fontWeight:400,color:"rgba(245,241,235,0.45)",lineHeight:1.55,maxWidth:540,marginTop:8}}>Your architect designs. Your builder constructs. But who ensures all parties are working in your interest — and that the project stays on track?</div></F></div></section>
<Sec py={120}><F><Ttl size="clamp(26px,3vw,34px)">Why This Service Exists</Ttl><Bd max={600}>Custom residential projects involve dozens of professionals making hundreds of decisions over 12\u201324 months. The builder\u2019s interests and the homeowner\u2019s interests are not always perfectly aligned — particularly around cost, scope changes, and specification substitutions. An owner\u2019s representative works exclusively for you.</Bd></F><F delay={0.08}><div style={{borderLeft:`2px solid ${C.orange}`,paddingLeft:28,marginTop:36}}><p style={{...sn,fontSize:13,fontWeight:500,color:C.text,marginBottom:8}}>What makes our representation different:</p><p style={{...sn,fontSize:14,fontWeight:300,lineHeight:1.85,color:C.muted,maxWidth:540}}>Brett has spent 25 years creating the drawings that builders build from. He reads construction documents the way a builder does, catches code conflicts before they reach permit, and understands where assumptions hide in a quote. This is technically informed advocacy — not general project management.</p></div></F>
{/* 8. Subtle visual proof cue */}
<F delay={0.16}><div style={{marginTop:56,padding:"28px 32px",background:C.warm,borderLeft:`2px solid ${C.faint}`,display:"flex",gap:20,alignItems:"center"}}><div style={{...sn,fontSize:32,color:C.stone,fontWeight:200,lineHeight:1}}>&#x25A1;</div><div><div style={{...sn,fontSize:9.5,fontWeight:500,letterSpacing:2.5,color:C.orange,textTransform:"uppercase",marginBottom:4}}>Documentation Standard</div><p style={{...sn,fontSize:13,fontWeight:300,color:C.muted,lineHeight:1.6}}>Every drawing set is coordinated across architectural, structural, and mechanical systems — reviewed as a single integrated package before submission.</p></div></div></F></Sec>
<Sec py={120} bg={C.warm}><F><Lbl>Who This Is For</Lbl></F><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))",gap:56,marginTop:24}}>{[{t:"Planning a Project",items:["Planning a custom home or major renovation and want expert guidance before committing","Need help evaluating lots, professionals, or contract terms","Want an independent expert to validate quotes before signing"]},{t:"Mid-Project and Need Help",items:["Experiencing delays, budget overruns, or communication breakdowns","Unsure whether change orders are legitimate or scope has drifted","Want ongoing independent oversight through completion"]}].map((c,i)=><F key={i} delay={i*0.08}><div style={{borderTop:`1px solid ${C.faint}`,paddingTop:32}}><h3 style={{...sn,fontSize:15,fontWeight:500,color:C.black,marginBottom:22}}>{c.t}</h3>{c.items.map((x,j)=><div key={j} style={{display:"flex",gap:14,marginBottom:14}}><span style={{...sn,fontSize:12,color:C.orange,fontWeight:500,minWidth:14,paddingTop:2}}>—</span><span style={{...sn,fontSize:13.5,fontWeight:300,color:C.muted,lineHeight:1.65}}>{x}</span></div>)}</div></F>)}</div></Sec>
<Sec py={120}><F><Lbl>How We Support the Project</Lbl></F><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(240px,1fr))",gap:48,marginTop:40}}>{[{t:"Drawing + Document Review",d:"Independent review of architectural, structural, and mechanical documents. We identify coordination gaps and constructability concerns before they become change orders."},{t:"Budget + Quote Validation",d:"Analysis of builder quotes, allowances, and contract terms. We identify embedded assumptions and areas of cost exposure."},{t:"Team Coordination",d:"Managing information flow between architect, designer, builder, and trades. Everyone works from the same assumptions."},{t:"Decision Support",d:"When you face a material, scope, or cost decision, we provide technical context and financial implications so you choose with confidence."}].map((x,i)=><F key={i} delay={i*0.06}><div style={{borderTop:`1px solid ${C.faint}`,paddingTop:28}}><h4 style={{...sn,fontSize:14,fontWeight:500,color:C.black,marginBottom:10}}>{x.t}</h4><p style={{...sn,fontSize:13,fontWeight:300,lineHeight:1.75,color:C.muted}}>{x.d}</p></div></F>)}</div></Sec>
<section style={{background:C.deep,padding:"100px 40px",textAlign:"center"}}><Ttl light size="clamp(26px,3vw,36px)">Want an experienced advocate in your corner?</Ttl><p style={{...sn,fontSize:14,fontWeight:300,color:"rgba(245,241,235,0.3)",maxWidth:420,margin:"0 auto 40px"}}>Available for projects at any stage and any budget.</p><Bt onClick={()=>go("contact")}>Request a Representation Consultation</Bt></section></>}

function AboutPage({go}){return <><section style={{background:C.black,padding:"180px 40px 120px"}}><div style={{maxWidth:940,margin:"0 auto"}}><F><Lbl light>Our Story</Lbl><Ttl light>Built on Precision. Now Building as a Family.</Ttl></F></div></section>
<Sec py={120}><F><div style={{...sn,fontSize:9.5,fontWeight:500,letterSpacing:3.5,textTransform:"uppercase",color:C.orange,marginBottom:20}}>Why Accurate Designs Exists</div><div style={{...sf,fontSize:"clamp(22px,3vw,30px)",color:C.black,lineHeight:1.4,marginBottom:28,maxWidth:580}}>Too many residential projects were going over budget — not because of bad design, but because critical decisions were being deferred to construction.</div><Bd max={580}>Accurate Designs was founded in 2000 to close that gap. The premise was straightforward: if zoning, structure, mechanical systems, and budget are coordinated during design, the project runs more smoothly and costs less to build.</Bd></F></Sec>
<Sec py={120} bg={C.warm}><F><div style={{...sn,fontSize:9.5,fontWeight:500,letterSpacing:3.5,textTransform:"uppercase",color:C.orange,marginBottom:20}}>How Brett Works</div><Bd max={600}>Over 300+ residential projects — from modest renovations to $20M+ estates — Brett has developed a consistent approach: coordinate every system on paper, anticipate construction realities during design, and produce documentation thorough enough that the builder\u2019s job is to execute, not interpret.</Bd></F><F delay={0.08}><Bd max={600}>The results are measurable. Permit submissions that typically receive 2\u20133 review comments. Builders who report that these are among the most complete drawings they work from. Projects where the design intent carries through to the finished home.</Bd></F></Sec>
<Sec py={120}><F><div style={{...sn,fontSize:9.5,fontWeight:500,letterSpacing:3.5,textTransform:"uppercase",color:C.orange,marginBottom:20}}>Where We're Going</div><Bd max={580}>Accurate Designs is expanding into a family-operated firm. Brett\u2019s wife brings VP-level corporate communications expertise to client experience and business operations. Their two sons are learning the practice — the next generation of a firm built on getting the details right.</Bd></F><F delay={0.08}><div style={{...sn,fontSize:13,fontWeight:500,color:C.black,marginTop:24}}>— Brett Lyver, Founder + Principal Designer</div></F></Sec>
<section style={{background:C.black,padding:"64px 40px"}}><div style={{maxWidth:940,margin:"0 auto"}}><Stats light/></div></section>
<Sec py={120} bg={C.warm}><F><Lbl>What Clients + Collaborators Say</Lbl></F><div style={{marginTop:40}}>{TEST.map((t,i)=><F key={i} delay={i*0.06}><div style={{borderTop:`1px solid ${C.faint}`,padding:"36px 0"}}><div style={{...sn,fontSize:9,fontWeight:500,letterSpacing:2.5,color:C.orange,marginBottom:12,textTransform:"uppercase"}}>{t.label}</div><p style={{...sf,fontSize:i<2?"clamp(17px,2vw,22px)":"clamp(15px,1.8vw,18px)",fontStyle:"italic",fontWeight:400,color:C.smoke,lineHeight:1.6,marginBottom:16,maxWidth:540}}>{t.text}</p><div style={{...sn,fontSize:12,fontWeight:500,color:C.black}}>{t.author}</div><div style={{...sn,fontSize:11,fontWeight:300,color:C.muted}}>{t.location}</div></div></F>)}</div></Sec>
<section style={{background:C.deep,padding:"100px 40px",textAlign:"center"}}><Ttl light size="clamp(26px,3vw,36px)">Ready to discuss your project?</Ttl><div style={{marginTop:36}}><Bt onClick={()=>go("contact")}>Book a Project Consultation</Bt></div></section></>}

function ContactPage({go}){const[sent,setSent]=useState(false);return <><section style={{background:C.black,padding:"180px 40px 120px",position:"relative",overflow:"hidden"}}><div style={{position:"absolute",inset:0,opacity:0.06}}><img src="https://accuratedesigns.ca/wp-content/uploads/2017/01/Brett-Custom-Homes-7-1.jpg" alt="" style={{width:"100%",height:"100%",objectFit:"cover",filter:"grayscale(100%)"}}/></div><div style={{position:"relative",maxWidth:940,margin:"0 auto"}}><F><Lbl light>Begin Here</Lbl><Ttl light>Book a Project Consultation</Ttl></F><F delay={0.1}><Bd light max={480}>A focused conversation about your project, your goals, and the right path forward. No cost, no obligation — just clarity.</Bd></F></div></section>
<Sec py={100} bg={C.warm}><div style={{display:"grid",gridTemplateColumns:"1.1fr 0.9fr",gap:100}} className="cg"><div>{sent?<F><div style={{padding:"80px 0"}}><div style={{...sf,fontSize:28,color:C.black,marginBottom:12}}>Thank you.</div><Bd>We've received your inquiry and will follow up within one business day.</Bd></div></F>:<><div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:"0 36px"}}><Inp label="First Name *"/><Inp label="Last Name *"/></div><Inp label="Email *" type="email"/><Inp label="Phone" type="tel"/><Sel label="Project Type" options={["Select...","Custom Home (New Build)","Major Addition","Major Renovation","Feasibility / Planning","Owner Representation","Other"]}/><Sel label="Service Needed" options={["Select...","Full Design-Build","Design + Permit Drawings","Permit Drawings Only","Owner Representation","Feasibility Review","Not Sure Yet"]}/><Inp label="Project Location"/><Sel label="Estimated Budget Range" options={["Select...","Under $500K","$500K \u2013 $1M","$1M \u2013 $3M","$3M \u2013 $5M","$5M \u2013 $10M","$10M+","Not Sure Yet"]}/><Sel label="Target Start Timeline" options={["Select...","Within 3 months","3\u20136 months","6\u201312 months","12+ months","Already in progress"]}/><Sel label="Drawing Status" options={["Select...","Starting from scratch","Conceptual / sketch stage","Design development","Permit-ready or permitted","Have drawings — need revisions"]}/><Sel label="Builder Status" options={["Select...","No builder yet","Evaluating builders","Builder selected — not signed","Builder under contract","Want Accurate Designs to build","Not applicable"]}/><Inp label="Project Overview" textarea/><p style={{...sn,fontSize:11,fontWeight:300,color:C.stone,marginBottom:24}}>Every inquiry is reviewed personally by our team.</p><Bt onClick={()=>setSent(true)} style={{width:"100%"}}>Submit Project Inquiry</Bt></>}</div>
<div style={{paddingTop:12}}><div style={{background:C.cream,padding:"32px 28px",marginBottom:32}}><h3 style={{...sf,fontSize:20,fontWeight:400,color:C.black,marginBottom:20}}>What Happens Next</h3>{["We review your inquiry and assess fit.","We follow up within one business day to schedule a call.","During the call, we discuss goals, assess feasibility, and outline next steps."].map((s,i)=><div key={i} style={{display:"flex",gap:16,marginBottom:16,alignItems:"flex-start"}}><div style={{...sn,fontSize:11,fontWeight:500,color:C.orange,minWidth:18,paddingTop:2}}>{i+1}.</div><p style={{...sn,fontSize:13,fontWeight:300,color:C.muted,lineHeight:1.65}}>{s}</p></div>)}</div>
<div style={{borderTop:`1px solid ${C.faint}`,paddingTop:28,marginTop:20,marginBottom:28}}>{[{l:"Email",v:"blyver@accuratedesigns.ca"},{l:"Phone",v:"416-768-1290"},{l:"Office",v:"1215 Queensway E, Unit 56\nMississauga, ON L4Y 1R6"}].map((c,i)=><div key={i} style={{marginBottom:20}}><div style={{...sn,fontSize:9.5,fontWeight:500,letterSpacing:2.5,textTransform:"uppercase",color:C.muted,marginBottom:5}}>{c.l}</div><div style={{...sn,fontSize:14,fontWeight:300,color:C.black,whiteSpace:"pre-line",lineHeight:1.6}}>{c.v}</div></div>)}</div>
<div style={{borderTop:`1px solid ${C.faint}`,paddingTop:28}}><div style={{...sn,fontSize:9.5,fontWeight:500,letterSpacing:2.5,textTransform:"uppercase",color:C.muted,marginBottom:10}}>Service Area</div><p style={{...sn,fontSize:13,fontWeight:300,lineHeight:1.75,color:C.muted}}>Greater Toronto Area including Milton, Oakville, Burlington, Mississauga, and Toronto. Muskoka, Niagara, and extended regions considered case-by-case.</p></div></div></div></Sec>
<style>{`@media(max-width:860px){.cg{grid-template-columns:1fr!important;gap:48px!important}}`}</style></>}

function Footer({go}){return <footer style={{background:C.black,padding:"72px 40px 48px",borderTop:"1px solid rgba(201,106,43,0.06)"}}><div style={{maxWidth:1100,margin:"0 auto"}}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(190px,1fr))",gap:44,marginBottom:56}}><div><div style={{display:"flex",alignItems:"center",gap:14,marginBottom:24}}><div style={{width:30,height:30,border:"1px solid rgba(255,255,255,0.12)",display:"flex",alignItems:"center",justifyContent:"center"}}><span style={{...sf,fontSize:14,fontWeight:500,color:"rgba(245,241,235,0.4)"}}>AD</span></div><span style={{...sn,fontSize:9,fontWeight:300,letterSpacing:4,color:"rgba(245,241,235,0.2)",textTransform:"uppercase"}}>Accurate Designs</span></div><p style={{...sn,fontSize:12,fontWeight:300,color:"rgba(245,241,235,0.2)",lineHeight:1.75}}>Construction-aware residential design since 2000.</p></div>
<div><div style={{...sn,fontSize:9,fontWeight:500,letterSpacing:3,color:"rgba(201,106,43,0.6)",marginBottom:18,textTransform:"uppercase"}}>Navigate</div>{[{id:"services",l:"Services"},{id:"portfolio",l:"Portfolio"},{id:"process",l:"Process"},{id:"owner-rep",l:"Owner Rep"},{id:"about",l:"About"},{id:"contact",l:"Contact"}].map(p=><div key={p.id} onClick={()=>go(p.id)} style={{...sn,fontSize:12,fontWeight:300,color:"rgba(245,241,235,0.25)",marginBottom:10,cursor:"pointer",transition:"color 0.3s"}} onMouseEnter={e=>e.target.style.color="rgba(245,241,235,0.55)"} onMouseLeave={e=>e.target.style.color="rgba(245,241,235,0.25)"}>{p.l}</div>)}</div>
<div><div style={{...sn,fontSize:9,fontWeight:500,letterSpacing:3,color:"rgba(201,106,43,0.6)",marginBottom:18,textTransform:"uppercase"}}>Services</div>{[{id:"services",l:"Design + Build"},{id:"owner-rep",l:"Owner Representation"},{id:"services",l:"Permit-Ready Documentation"},{id:"services",l:"Feasibility Review"}].map((s,i)=><div key={i} onClick={()=>go(s.id)} style={{...sn,fontSize:12,fontWeight:300,color:"rgba(245,241,235,0.25)",marginBottom:10,cursor:"pointer",transition:"color 0.3s"}} onMouseEnter={e=>e.target.style.color="rgba(245,241,235,0.55)"} onMouseLeave={e=>e.target.style.color="rgba(245,241,235,0.25)"}>{s.l}</div>)}</div>
<div><div style={{...sn,fontSize:9,fontWeight:500,letterSpacing:3,color:"rgba(201,106,43,0.6)",marginBottom:18,textTransform:"uppercase"}}>Contact</div><div style={{...sn,fontSize:12,fontWeight:300,color:"rgba(245,241,235,0.2)",lineHeight:1.8}}>Accurate Designs Inc.<br/>1215 Queensway E, Unit 56<br/>Mississauga, ON L4Y 1R6<br/>416-768-1290</div><div style={{...sn,fontSize:11,fontWeight:300,color:"rgba(245,241,235,0.12)",marginTop:18,lineHeight:1.6,fontStyle:"italic"}}>Consultation · Feasibility · Representation</div></div></div>
<div style={{borderTop:"1px solid rgba(245,241,235,0.04)",paddingTop:32,display:"flex",justifyContent:"space-between",flexWrap:"wrap",gap:16,alignItems:"center"}}><span style={{...sn,fontSize:11,fontWeight:300,color:"rgba(245,241,235,0.15)"}}>{"\u00a9"} 2026 Accurate Designs Inc.</span><span style={{...sf,fontSize:12,fontWeight:400,fontStyle:"italic",color:"rgba(245,241,235,0.1)",letterSpacing:0.5}}>Resolve complexity before it reaches the site.</span></div></div></footer>}

export default function App(){const[page,setPage]=useState("home");const go=useCallback(p=>{setPage(p);window.scrollTo({top:0,behavior:"instant"})},[]);const pages={home:<HomePage go={go}/>,services:<ServicesPage go={go}/>,portfolio:<PortfolioPage go={go}/>,process:<ProcessPage go={go}/>,"owner-rep":<OwnerRepPage go={go}/>,about:<AboutPage go={go}/>,contact:<ContactPage go={go}/>};return <div style={{...sn,fontWeight:300,color:C.muted,background:C.cream,minHeight:"100vh"}}><Nav page={page} go={go}/>{pages[page]||pages.home}<Footer go={go}/></div>}
